name: Playwright Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      id: run_tests
      run: node runTest.js
      continue-on-error: true  # Continue even if tests fail, so we can handle the failure

    - name: Upload Playwright report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Revert commit if tests fail
      if: failure()  # If the previous step failed, revert the commit
      run: |
        echo "Tests failed, reverting the last commit..."
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git revert --no-edit HEAD
        git push origin HEAD

    - name: Notify success or failure
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "Tests passed!";
        else
          echo "Tests failed and the commit has been reverted.";
        fi
